accounts/urls.py
from django.urls import path
from .views import UserRegistrationView, UserLoginView, UserLogoutView, UserUpdateView
# from django.contrib.auth.views import LogoutView
urlpatterns = [
    path('register/',UserRegistrationView.as_view(), name='register'),
    path('login/',UserLoginView.as_view(), name='user_login'),
    path('logout/',UserLogoutView.as_view(), name='user_logout'),
    path('profile/',UserUpdateView.as_view(), name='profile'),
]

mamar_bank/urls.py
from django.contrib import admin
from django.urls import path,include
from core.views import HomeView
urlpatterns = [
    path('', HomeView.as_view(), name='homepage'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('transactions/', include('transactions.urls')),
]

transactions/urls.py
from django.urls import path
from .views import DepositMoneyView, WithdrawMoneyView, LoanRequestView, LoanListView, PayLoanView, TransactionReportView

urlpatterns = [
    path("deposit/",DepositMoneyView.as_view(), name="deposit_money"),
    path("report/",TransactionReportView.as_view(), name="transaction_report"),
    path("withdraw/",WithdrawMoneyView.as_view(), name="withdraw_money"),
    path("loan_request/",LoanRequestView.as_view(), name="loan_request"),
    path("loans/",LoanListView.as_view(), name="loan_list"),
    path("deposit/<int:loan_id>/",PayLoanView.as_view(), name="pay_loan"),
    
]

transactions/models.py
from django.db import models
from accounts.models import UserBankAccount
from .constants import TRANSACTION_TYPE
# Create your models here.

# Akta User Deposit, Withdraw, Loan agula korte paarbe!

class TransactionModel(models.Model):
    # akjon user er multiple type transactions hoite paare!
    account = models.ForeignKey(UserBankAccount, related_name='transactions', on_delete=models.CASCADE)
    amount = models.DecimalField(decimal_places=2, max_digits=15)
    balance_after_transaction = models.DecimalField(decimal_places=2, max_digits=15)
    transaction_type = models.IntegerField(choices=TRANSACTION_TYPE, null= True)
    timestamp = models.DateTimeField(auto_now_add=True)
    loan_approve = models.BooleanField(default=False, null= True)
    
    class Meta:
        ordering = ['timestamp']

transactions/forms.py
from django import forms
from .models import TransactionModel

class TransactionForm(forms.ModelForm):
    class Meta:
        model = TransactionModel
        fields = ['amount', 'transaction_type']
        
    def __init__(self, *args, **kwargs):
        self.account = kwargs.pop('account') #account taake er kore anbo!
        super().__init__(*args, **kwargs)
        self.fields['transaction_type'].disabled = True #1st a ai field ta disabled thaakbe
        self.fields['transaction_type'].widget = forms.HiddenInput() #User er theke hide kora thaakbe!
        
    def save(self, commit=True):
        self.instance.account = self.account # jei user ta request kortese tar kono object db te thakle tar instance er account a jabo giye ai kaajta ta korbo!
        self.instance.balance_after_transaction = self.account.balance
        return super().save()
    
class DepositForm(TransactionForm):
    def clean_amount(self): # amount field ke filter/update korbo
        min_deposit_amount = 100
        amount = self.cleaned_data.get('amount') # user er fillup kora form theke amra amount field er value ke niye ashlam! (Example: 500)
        if amount < min_deposit_amount:
            raise forms.ValidationError(
                f'You need to deposit at least {min_deposit_amount} $'
            )
        return amount
    
class WithdrawForm(TransactionForm):
    def clean_amount(self):
        account = self.account # user er BankAccount
        min_withdraw_amount = 500
        max_withdraw_amount = 100000
        balance = account.balance
        amount = self.cleaned_data.get('amount')  # user er fillup kora form theke amra amount field er value ke niye ashlam! (Example: 500)
        if amount < min_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at least {min_withdraw_amount} $'
            )
        if amount > max_withdraw_amount:
            raise forms.ValidationError(
                f'You can withdraw at most {max_withdraw_amount} $'
            )
        if amount > balance: # amount = 5000, tar balance ache 200
            raise forms.ValidationError(
                f"You've {balance} $ in your account. "
                "You can't withdraw more than your account balance"
            )
        return amount
    
    
class LoanRequestForm(TransactionForm):
    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        
        return amount

transactions/views.py
from django.shortcuts import render
from django.views.generic import CreateView, ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import TransactionModel
from .forms import DepositForm, WithdrawForm, LoanRequestForm
from .constants import DEPOSIT, WITHDRAWAL, LOAN, LOAN_PAID
from django.contrib import messages
from django.http import HttpResponse
from datetime import datetime
from django.db.models import Sum
from django.views import View
from django.shortcuts import get_object_or_404,redirect
from django.urls import reverse_lazy
from django.core.mail import EmailMessage, EmailMultiAlternatives
from django.template.loader import render_to_string
# Create your views here.

def sendTransactionEmail(user, amount, subject,template):
    message = render_to_string(template,{
        'user': user,
        'amount': amount
    })
    send_email = EmailMultiAlternatives(subject,'',to=[user.email])
    send_email.attach_alternative(message,"text/html")
    send_email.send()

class TransactionCreateMixin(LoginRequiredMixin,CreateView):
    template_name = 'transaction_form.html'
    model = TransactionModel
    title = ''
    success_url = reverse_lazy('transaction_report')
    
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs.update({
            'account' : self.request.user.account, 
        })
        return kwargs
    
    #This method is used to populate a dictionary to use as the template context. 
    # You will probably be overriding this method most often to add things to display in your templates.
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'title': self.title
        })
        return context

class DepositMoneyView(TransactionCreateMixin):
    form_class = DepositForm
    title = 'Deposit' # built-in keyword na
    
    def get_initial(self):
        initial = {'transaction_type': DEPOSIT}
        return initial
    
    # if form.is_valid(): 
    def form_valid(self,form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        account.balance += amount
        account.save(
            update_fields = ['balance']
        )
        
        messages.success(self.request,f"{amount} $ was deposited to your account successfully!")
        
        sendTransactionEmail(self.request.user,amount,"Deposit Message",'deposit_email.html')
        
        return super().form_valid(form)
    
class WithdrawMoneyView(TransactionCreateMixin):
    form_class = WithdrawForm
    title = 'Withdraw Money' # built-in keyword na
    
    # Backend theke dekha jabe initially
    def get_initial(self):
        initial = {'transaction_type': WITHDRAWAL}
        return initial
    
    # if form.is_valid(): 
    def form_valid(self,form):
        amount = form.cleaned_data.get('amount')
        account = self.request.user.account
        account.balance -= amount
        account.save(
            update_fields = ['balance']
        )
        messages.success(self.request,f"{amount} $ was withdrawn from your account successfully!")
        
        sendTransactionEmail(self.request.user,amount,"Withdrawal Message",'withdrawal_email.html')
        
        return super().form_valid(form)
    
    
class LoanRequestView(TransactionCreateMixin):
    form_class = LoanRequestForm
    title = 'Request For Loan' # built-in keyword na
    
    # Backend theke dekha jabe initially
    def get_initial(self):
        initial = {'transaction_type': LOAN}
        return initial
    
    # if form.is_valid(): 
    def form_valid(self,form):
        amount = form.cleaned_data.get('amount')
        
        # User'r kotogula laon approve hoise seita count korbo
        current_loan_count = TransactionModel.objects.filter(account= self.request.user.account, transaction_type= LOAN,loan_approve=True).count()
        
        if current_loan_count >=3 :
            return HttpResponse("You crossed your loan limit")
        messages.success(self.request,f"Loan request for {amount} $ has been successfully sent to admin!")
        
        sendTransactionEmail(self.request.user,amount,"Loan Request Message",'loan_email.html')
        
        return super().form_valid(form) # form taake amar jinishgula diye overright kore dilaam



class TransactionReportView(LoginRequiredMixin, ListView):
    template_name = 'transaction_report.html'
    model = TransactionModel
    balance = 0
    context_object_name = 'report_list'
    
    def get_queryset(self):
        # jodi user kono type filter na kore tahole taar total transaction report dekhabo!
        queryset = super().get_queryset().filter(
            account = self.request.user.account
        )
        start_date_str =  self.request.GET.get('start_date')
        end_date_str =  self.request.GET.get('end_date')
        
        if start_date_str and end_date_str:
            start_date = datetime.strptime(start_date_str, "%Y-%m-%d").date()
            end_date = datetime.strptime(end_date_str, "%Y-%m-%d").date()
            queryset = queryset.filter(timestamp__date__gte = start_date, timestamp__date__lte = end_date)
            self.balance = TransactionModel.objects.filter(timestamp__date__gte = start_date, timestamp__date__lte = end_date).aggregate(Sum('amount'))
            ['amount_sum']
        else:
            self.balance = self.request.user.account.balance
        
        return queryset.distinct()
    
    # context hisebe 'account' ke pathabo!
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context.update({
            'account': self.request.user.account
        })
        return context
    
class PayLoanView(LoginRequiredMixin, View):
    def get(self, request, loan_id):
        loan = get_object_or_404(TransactionModel, id=loan_id)
        
        if loan.loan_approve: # akjon user loan pay korte paarbe tokhoni jokhon taar loan approve hobe!
            user_account = loan.account
            if loan.amount < user_account.balance:
                user_account.balance -= loan.amount # current balance theke loan amount baad disi!
                loan.balance_after_transaction = user_account.balance # balance after transaction ke current balance diye replace korlam!
                user_account.save()
                loan.transaction_type = LOAN_PAID
                loan.save()
                return redirect('loan_list')
            else:
                messages.error(self.request,f"Loan amount is greater than available balance")
        return redirect('loan_list')
            
# class LoanListView(LoginRequiredMixin, ListView):
#     model = TransactionModel
#     template_name = 'loan_request.html'
#     context_object_name = 'loans'
    
#     def get_queryset(self):
#         user_account = self.request.user.account
#         queryset = TransactionModel.objects.filter(account=user_account,transaction_type=LOAN)
#         return queryset
class LoanListView(LoginRequiredMixin,ListView):
    model = TransactionModel
    template_name = 'loan_request.html'
    context_object_name = 'loans' # loan list ta ei loans context er moddhe thakbe

    def get_queryset(self):
        user_account = self.request.user.account
        queryset = TransactionModel.objects.filter(account=user_account,transaction_type=LOAN)
        print(queryset)
        return queryset
    

transactions/templates/admin_email.html
<h4>Hello {{user.first_name}} {{user.last_name}}</h4>

<h2>COngratulations!!! Your Loan Request has been approved</h2>
<p>After loan approval your total amount is ${{user.account.balance}}</p>

<p>Thanks for banking with us.</p>
<p>Mamar Bank Team</p>

transactions/templates/deposit_email.html
<h4>Hello {{user.first_name}} {{user.last_name}}</h4>

<p>Your Deposit Request for ${{amount}} has been successfully completed. After deposit your total amount is ${{user.account.balance}}</p>

<p>Thanks for banking with us.</p>
<p>Mamar Bank Team</p>

transactions/templates/loan_email.html
<h4>Hello {{user.first_name}} {{user.last_name}}</h4>

<p>Your Loan Request for ${{amount}} has been successfully sent to admin. Wait for admin approval. After getting admin approval you'll get the loan and also get the confirmation mail.</p>

<p>Thanks for banking with us.</p>
<p>Mamar Bank Team</p>

transactions/templates/loan_request.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %} 
{% block body %}
<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
    <h1 class="font-bold text-3xl text-center pb-5 pt-2">Loan Report</h1>
    <hr />
    <table class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500">
        <thead class="bg-purple-900 text-white text-left">
            <tr class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold">
                <th class="px-4 py-2">LOAN ID</th>
                <th class="px-4 py-2">Loan Amount</th>
                <th class="px-4 py-2">Loan Approved</th>
                <th class="px-4 py-2">Action</th>
            </tr>
        </thead>
        <tbody>
        {% for loan in loans %}
            <tr class="border-b dark:border-neutral-500">
            <td class="px-4 py-2">
                {{ loan.id }}
            </td>
            <td class="px-4 py-3 text-s border">
                <span class="px-2 py-1 font-bold leading-tight rounded-sm text-green-700 bg-green-100">
                    {{ loan.amount }}
                </span>
            </td>
            <td class="px-4 py-2">
                {{ loan.loan_approve }}
            </td>
            <td class="px-4 py-2">
                {% if loan.loan_approve %}
                    <a class="font-bold bg-red-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" href='{% url "pay_loan" loan.id %}'>Pay</a>
                {% else %}
                    <p class="font-bold text-red-700 bg-red-100">Loan Pending</p>
                {% endif %}
            </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

transactions/templates/transaction_form.html
{% extends 'base.html' %} 
{% block head_title %}{{ title }}{% endblock %} 
{% block body %}
{% comment %} <h1>{{title}}</h1> {% endcomment %}
<div class="w-full flex mt-5 justify-center ">
    <div class="bg-white w-5/12 rounded-lg">
        {% if title == 'Request For Loan' %}
            <div>
                <a class="font-bold text-blue text-center pb-5 pt-10 px-5" href="{% url 'loan_list' %}">View All Loan List</a>
            </div>
        {% endif %}
        <h1 class="font-bold text-3xl text-center pb-5 pt-10 px-5">{{ title }}</h1>
        <form method="post" class="px-8 pt-6 pb-8 mb-4">
            {% csrf_token %}

            <div class="mb-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="amount">
                    Amount
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight border rounded-md border-gray-500 focus:outline-none focus:shadow-outline" name="amount" id="amount" type="number" required placeholder="Amount">
            </div>

            <!--Form er Validation Error er jonno-->
            {% if form.amount.errors %} {% for error in form.amount.errors %}
            <p class="text-red-600 text-sm italic pb-2">{{ error }}</p>
            {% endfor %} {% endif %}
            <div class="flex w-full justify-center">
                <button class="bg-blue-900 text-white hover:text-blue-900 hover:bg-white border border-blue-900 font-bold px-4 py-2 rounded-lg" type="submit">
                    Submit
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

transactions/templates/transaction_report.html
{% extends 'base.html' %} 
{% load static %}
{% load humanize %}
{% block head_title %} Transaction Report{% endblock %}
{% block body %}

{% include 'messages.html'%}
<div class="my-10 py-3 px-4 bg-white rounded-xl shadow-md">
    <h1 class="font-bold text-3xl text-center pb-5 pt-2">Transaction Report</h1>
    <hr/>
    <form method="get" action="{% url 'transaction_report' %}">
        <div class="flex justify-center">
            <div class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12 mx-2">
                <label for="start_date">From:</label>
                <input class="appearance-none w-full outline-none focus:outline-none active:outline-none" 
                type="date" 
                id="start_date"
                name="start_date"/>
            </div>

            <div class="mt-10 pl-3 pr-2 bg-white border rounded-md border-gray-500 flex justify-between items-center relative w-4/12">
                <label for="end_date">To:</label>
                <input class="appearance-none w-full outline-none focus:outline-none active:outline-none"
                type="date"
                id="end_date"
                name="end_date"/>
            </div>
            
            <div class="mt-10 pl-3 pr-2 flex justify-between items-center relative w-4/12">
                <button class="bg-blue-900 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
                    Filter
                </button>
            </div>
        </div>
    </form>
<table class="table-auto mx-auto w-full px-5 rounded-xl mt-8 border dark:border-neutral-500">
    <thead class="bg-purple-900 text-white text-left">
        <tr class="bg-gradient-to-tr from-indigo-600 to-purple-600 rounded-md py-2 px-4 text-white font-bold">
            <th class="px-4 py-2">Date</th>
            <th class="px-4 py-2">Transaction Type</th>
            <th class="px-4 py-2">Amount</th>
            <th class="px-4 py-2">Balance After Transaction</th>
        </tr>
    </thead>
    
    <tbody>
    {% for transaction in report_list %}
    <tr class="border-b dark:border-neutral-500">
        <td class="px-4 py-2">
            {{ transaction.timestamp|date:"F d, Y h:i A" }}
        </td>
        <td class="px-4 py-3 text-s border">
        <span class="px-2 py-1 font-bold leading-tight rounded-sm 
        {% if transaction.get_transaction_type_display == 'Withdraw' %} text-red-700 bg-red-100 
        {% else %} text-green-700 bg-green-100 {% endif %}">
            {{ transaction.get_transaction_type_display }}
        </span>
        </td>
        <td class="px-4 py-2">
        $ {{ transaction.amount|floatformat:2|intcomma }}
        </td>
        <td class="px-4 py-2">
        $ {{ transaction.balance_after_transaction|floatformat:2|intcomma }}
        </td>
    </tr>
    {% endfor %}
    <tr class="bg-gray-800 text-white">
        <th class="px-4 py-2 text-right" colspan="3">Current Balance</th>
        <th class="px-4 py-2 text-left">
        $ {{ account.balance|floatformat:2|intcomma }}
        </th>
    </tr>
    </tbody>
</table>
</div>
{% endblock %}

transactions/templates/withdrawal_email.html
<h4>Hello {{user.first_name}} {{user.last_name}}</h4>

<p>Your Withdrawal Request for ${{amount}} has been successfully completed. After withdraw your total amount is ${{user.account.balance}}</p>

<p>Thanks for banking with us.</p>
<p>Mamar Bank Team</p>